language: scala
sudo: false
scala:
  - 2.11.12
  - 2.12.7
  - 2.13.0-M4
jdk:
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.7
    jdk: oraclejdk9
  - scala: 2.12.7
    jdk: oraclejdk10
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier
script: 
  - travis_retry "./travis.sh"
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
